[package]
name = "beam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.47"
clearscreen = "1.0.7"
home = "0.5.3"
indicatif = "0.16.2"
pad = "0.1.6"
serde = {version="1.0.130", features=["derive"]}
serde_json = "1.0.71"
skim = "0.9.4"
structopt = "0.3.25"
toml = "0.5.8"
whoami = "1.2.0"
